In [9]:
import numpy as np
x=np.asarray([np.asarray([1,2,3]),np.asarray([4,5,6]), np.asarray([7,8,9])])
print(x)
cov=np.cov(x)
print(cov)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
